### ISSUE TITLE
IR Grammar incomplete. Have you considered https://github.com/llir

### ISSUE THREAD

**Issue by nielsenko** [praeclarum/Iril#2]
The problem with LLVM IR is that it is only defined by code, hence you need to reconstruct the grammar :-/

But other people have tried before. I was wondering if you are aware of https://github.com/llir/grammar/blob/master/ll.tm

They claim here: https://github.com/llir/llvm/blob/8a20cc8910c5223df2a22cbf0a50beb391a08131/HISTORY.md
that it is complete for LLVM 8.

It is not directly compatible with jay, but it is an EBNF. Perhaps it can be of use to you while developing Iril?

**Comment by praeclarum** [comment]
Thanks for the pointer!

There's not much benefit to parsing things that I cannot compile so I'm happy with my incremental grammar.

It will certainly make a good reference though, thanks again!
